name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform access token  
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    
      - name: Run JFrog CLI
        run: |
           #Ping the server
           #jf rt ping
           #Collect environment variables from the build
           jf rt bce
           #Collect VCS details from git and add them to the build
           jf rt bag
           # Publish build info
           jf rt bp
           # upload index.js the repository
           jf rt u index_0.0.3.js local-artifactory
           # upload nodeapp.tar into repository
           jf rt u nodeapp_0.0.3.tar local-artifactory
           # upload app.js into local-repository
           jf rt u app_0.0.3.js local-artifactory
           #Publish build info
           echo "Copy index.js, app.js, nodeapp.tar into local-repository successfully !"
